AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aws-lambda-band-application

  Sample SAM Template for aws-lambda-band-application
  
Globals:
  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"
  Function:
    Timeout: 3

Parameters:
  CognitoUserPoolName:
    Type: String
    Default: StudioManager
  
  CognitoUserPoolClientName:
    Type: String
    Default: StudioManager

Resources:
  GetBandFunction:
    Type: AWS::Serverless::Function
    Properties:
      Role: arn:aws:iam::258390702311:role/StudioManagerRole
      CodeUri: band-application/
      Handler: app.getBand
      Runtime: nodejs10.x
      Events:
        GetBand:
          Type: Api
          Properties:
            Path: /bands/{bandid}
            Method: get
  GetAllBandsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Role: arn:aws:iam::258390702311:role/StudioManagerRole
      CodeUri: band-application/
      Handler: app.getAllBands
      Runtime: nodejs10.x
      Events:
        GetBand:
          Type: Api
          Properties:
            Path: /bands
            Method: get
  PostBandFunction:
    Type: AWS::Serverless::Function
    Properties:
      Role: arn:aws:iam::258390702311:role/StudioManagerRole
      CodeUri: band-application/
      Handler: app.postBand
      Runtime: nodejs10.x
      Events:
        GetBand:
          Type: Api
          Properties:
            Path: /bands
            Method: post
  PutBandFunction:
    Type: AWS::Serverless::Function
    Properties:
      Role: arn:aws:iam::258390702311:role/StudioManagerRole
      CodeUri: band-application/
      Handler: app.putBand
      Runtime: nodejs10.x
      Events:
        GetBand:
          Type: Api
          Properties:
            Path: /bands/{bandid}
            Method: put
  DeleteBandFunction:
    Type: AWS::Serverless::Function
    Properties:
      Role: arn:aws:iam::258390702311:role/StudioManagerRole
      CodeUri: band-application/
      Handler: app.deleteBand
      Runtime: nodejs10.x
      Events:
        GetBand:
          Type: Api
          Properties:
            Path: /bands/{bandid}
            Method: delete

# Outputs:
#   # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
#   # Find out more about other implicit resources you can reference within SAM
#   # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
#   HelloWorldApi:
#     Description: "API Gateway endpoint URL for Prod stage for Hello World function"
#     Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
#   HelloWorldFunction:
#     Description: "Hello World Lambda Function ARN"
#     Value: !GetAtt HelloWorldFunction.Arn
#   HelloWorldFunctionIamRole:
#     Description: "Implicit IAM Role created for Hello World function"
#     Value: !GetAtt HelloWorldFunctionRole.Arn
